services:
  gatewayservice:
    image: nikirenegade/ihb-gatewayservice:1.0.4
    port: 8000

  userservice:
    image: nikirenegade/ihb-userservice:1.0.5-api
    port: 8000
    rabbitmq: true
    migration:
      enabled: true
      image: nikirenegade/ihb-userservice:1.0.0-migration
  billingservice:
    image: nikirenegade/ihb-billingservice:1.0.0-api
    port: 8000
    rabbitmq: true
    migration:
      enabled: true
      image: nikirenegade/ihb-billingservice:1.0.0-migration
  
  deliveryservice:
    image: nikirenegade/ihb-deliveryservice:1.0.1-api
    port: 8000
    rabbitmq: false
    migration:
      enabled: true
      image: nikirenegade/ihb-deliveryservice:1.0.0-migration
  
  inventoryservice:
    image: nikirenegade/ihb-inventoryservice:1.0.0-api
    port: 8000
    rabbitmq: false
    migration:
      enabled: true
      image: nikirenegade/ihb-inventoryservice:1.0.0-migration
  
  orderservice:
    image: nikirenegade/ihb-orderservice:1.0.10-api
    port: 8000
    rabbitmq: true
    migration:
      enabled: true
      image: nikirenegade/ihb-orderservice:1.0.0-migration

  notificationservice:
    image: nikirenegade/ihb-notificationservice:1.0.0-api
    port: 8000
    rabbitmq: true
    migration:
      enabled: true
      image: nikirenegade/ihb-notificationservice:1.0.0-migration

jwt:
  key: "super_secret_key_12345_super_secret_key_67890"
  issuer: "ihbplatform"
  audiences:
    - "ihbplatform"
    - "internal"

rabbitmq:
  host: "rabbitmq"
  port: "5672"
  secretName: rabbitmq-default-user