# Secret с подключением к базе данных deliveriesdb; хранить вне репозитория в реальном кластере
apiVersion: v1
kind: Secret
metadata:
  name: deliveryservice-secret
type: Opaque
stringData:
  ConnectionStrings__deliverydbconnection: "Host=deliveries-db-postgresql;Port=5432;Database=deliveriesdb;Username=postgres;Password=P@SSw0rd"