# Secret с подключением к базе данных inventorysdb; хранить вне репозитория в реальном кластере
apiVersion: v1
kind: Secret
metadata:
  name: inventoryservice-secret
type: Opaque
stringData:
  ConnectionStrings__inventorydbconnection: "Host=inventories-db-postgresql;Port=5432;Database=inventoriesdb;Username=postgres;Password=P@SSw0rd"