# Secret с подключением к базе данных ordersdb; хранить вне репозитория в реальном кластере
apiVersion: v1
kind: Secret
metadata:
  name: orderservice-secret
type: Opaque
stringData:
  ConnectionStrings__orderdbconnection: "Host=orders-db-postgresql;Port=5432;Database=ordersdb;Username=postgres;Password=P@SSw0rd"
  ConnectionStrings__redis: "redis-master:6379,password=redispassword"