<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\Shared.RabbitMq\Shared.RabbitMq.csproj" />
    <ProjectReference Include="..\..\..\Shared\Shared.ServiceToken\Shared.ServiceToken.csproj" />
    <ProjectReference Include="..\..\Application\OrderService.Application\OrderService.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
