# Secret с подключением к базе данных usersdb; хранить вне репозитория в реальном кластере
apiVersion: v1
kind: Secret
metadata:
  name: billingservice-secret
type: Opaque
stringData:
  ConnectionStrings__billingdbconnection: "Host=billings-postgres-postgresql;Port=5432;Database=billingsdb;Username=postgres;Password=P@SSw0rd"