# Secret с подключением к базе данных notificationsdb; хранить вне репозитория в реальном кластере
apiVersion: v1
kind: Secret
metadata:
  name: notificationservice-secret
type: Opaque
stringData:
  ConnectionStrings__notificationdbconnection: "Host=notifications-db-postgresql;Port=5432;Database=notificationsdb;Username=postgres;Password=P@SSw0rd"