# Secret с подключением к базе данных usersdb; хранить вне репозитория в реальном кластере
apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
stringData:
  ConnectionStrings__userdbconnection: "Host=users-postgres-postgresql;Port=5432;Database=usersdb;Username=postgres;Password=P@SSw0rd"
