<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\DeliveryService.Domain\DeliveryService.Domain.csproj" />
    <ProjectReference Include="..\..\Domain\DeliveryService.Domain.Interfaces\DeliveryService.Domain.Interfaces.csproj" />
    <ProjectReference Include="..\DeliveryService.Infrastructure.EntityFramework\DeliveryService.Infrastructure.EntityFramework.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
