apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
stringData:
  Jwt__Key: "SUPER_SECRET_KEY_12345_SUPER_SECRET_KEY"
  Jwt__Issuer: "ihbplatform"
  Jwt__Audience: "ihbplatform"

#WARNING: You should not place the username and password in the version control repository or anywhere else in plain text.
#Instead, use the Services Tool Window -> Kubernetes -> <Desired Cluster> -> Configuration -> <right-click on Secrets> -> Create New Secret...
