<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\NotificationService.Domain\NotificationService.Domain.csproj" />
    <ProjectReference Include="..\..\Domain\NotificationService.Domain.Interfaces\NotificationService.Domain.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappers\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Services\.gitkeep" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
